### PR TITLE
Move ws2812 code into components folder

### PR DESCRIPTION
**Pull request by paulo-raca**
Which is the convention for the IDF

### CODE REVIEW

**Comment by MartyMacGyver** [comment]
Just so I'm clear on this, this to conform to the following spec, correct?

https://esp-idf.readthedocs.io/en/latest/api-guides/build-system.html#example-project

**Comment by paulo-raca** [comment]
Exactly -- Sorry I wasn't clear about it

**Comment by MartyMacGyver** [comment]
No, just double-checking (and this way the doc ref is part of the pull req).

**Comment by MartyMacGyver** [comment]
Thank you for your contribution! :100:

**Pull request merged**
